modules/admin/controllers/ArticleController.php
<?php

namespace app\modules\admin\controllers;

use app\models\db\ArticleRubric;
use app\models\db\Rubric;
use Yii;
use app\models\db\Article;
use yii\base\Exception;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * ArticleController implements the CRUD actions for Article model.
 */
class ArticleController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Article models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Article::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Article model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Article model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Article();

        if ($model->load(Yii::$app->request->post()) and $model->validate()) {

            /** Устанавливаем превью картинки */
            if($file = UploadedFile::getInstance($model, 'image')) {

                /** Генерируем имя файла */
                $filename = md5(Yii::$app->security->generateRandomString()).".".$file->extension;

                if($uploaded = $file->saveAs(Yii::getAlias("@webroot/upload/{$filename}"))) {
                    $model->image = Yii::getAlias("@web/upload/{$filename}");
                } else {
                    $model->image = $model->oldAttributes['image'];
                }
            } else {
                $model->image = $model->oldAttributes['image'];
            }

            /** Сохраняем */
            if($model->save()) {
                Yii::$app->session->addFlash('success', 'Новость успешно была добавлена');
            } else {
                Yii::$app->session->addFlash('error', 'Ошибка сохранения новости');
            }

            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Article model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException|Exception if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) and $model->validate()) {

            /** Устанавливаем превью картинки */
            if($file = UploadedFile::getInstance($model, 'image')) {

                /** Генерируем имя файла */
                $filename = md5(Yii::$app->security->generateRandomString()).".".$file->extension;

                if($uploaded = $file->saveAs(Yii::getAlias("@webroot/upload/{$filename}"))) {
                    $model->image = Yii::getAlias("@web/upload/{$filename}");
                } else {
                    $model->image = $model->oldAttributes['image'];
                }
            } else {
                $model->image = $model->oldAttributes['image'];
            }

            /** Сохраняем */
            if($model->save()) {
                Yii::$app->session->addFlash('success', 'Новость успешно была обновлена');
            } else {
                Yii::$app->session->addFlash('error', 'Ошибка обновления новости');
            }

            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * @param $id
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException
     */
    public function actionRubrics($id)
    {
        $model = $this->findModel($id);

        /** Есть отправленная форма */
        if (Yii::$app->request->isPost) {

            /** Смотрим переданные рубрики */
            if($_POST['rubrics']) {

                /** Удаляем все рубрики */
                ArticleRubric::deleteAll(['article_id' => $model->id]);

                /** Перебираем полученные рубрики как ID рубрики => 1/0 и сохраняем, если рубрика выбрана */
                foreach ($_POST['rubrics'] as $rubric_id => $value) {

                    /** Добавляем привязку статьи к рубрике */
                    if($value and (new ArticleRubric(['article_id' => $model->id, 'rubric_id' => $rubric_id]))->save()) {
                        Yii::$app->session->addFlash('success', 'Рубрика успешно добавлена');
                    }
                }
            }

            return $this->redirect(['view', 'id' => $model->id]);
        }

        /** Массив рубрик для привязки */
        $rubrics = Rubric::find()->select(['name'])->where(['deleted' => false])->indexBy('id')->column();

        return $this->render('rubrics', [
            'model' => $model,
            'rubrics' => $rubrics,
        ]);
    }

    /**
     * Deletes an existing Article model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Article model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Article the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Article::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

modules/admin/controllers/IdentityController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\models\db\Identity;
use yii\base\Exception;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * IdentityController implements the CRUD actions for Identity model.
 */
class IdentityController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Identity models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Identity::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Identity model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Identity model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     * @throws Exception
     */
    public function actionCreate()
    {
        $model = new Identity();

        if ($model->load(Yii::$app->request->post()) and $model->validate()) {

            $model->generatePassword($model->password);

            if($model->save()) {

                Yii::$app->session->setFlash('success', 'Пользователь добавлен');

                return $this->redirect(['view', 'id' => $model->id]);
            } else {

                Yii::$app->session->setFlash('error', 'Пользователь не добавлен');
            }

        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Identity model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     * @throws Exception
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) and $model->validate()) {

            $model->generatePassword($model->password);

            if($model->save()) {

                Yii::$app->session->setFlash('success', 'Пользователь изменен');

                return $this->redirect(['view', 'id' => $model->id]);
            } else {

                Yii::$app->session->setFlash('error', 'Пользователь не изменен');
            }

            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Identity model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Identity model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Identity the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Identity::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

modules/admin/views/article/_form.php
<?php

use dosamigos\tinymce\TinyMce;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\db\Article */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="article-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'image')->fileInput() ?>

    <?= $form->field($model, 'body')->widget(TinyMce::class, [
        'options' => ['rows' => 40, 'contenteditable' => true],
        'language' => 'ru',
        'clientOptions' => [
            'plugins' => [
                'advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker',
                'searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking',
                'save table contextmenu directionality emoticons template paste textcolor'
            ],
            'toolbar' => "undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | forecolor backcolor emoticons',",
            'paste_data_images' => true
        ]
    ]);?>

    <?= $form->field($model, 'deleted')->checkbox() ?>

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/admin/views/article/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\db\Article */

$this->title = 'Добавить новость';
$this->params['breadcrumbs'][] = ['label' => 'Новости', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="article-create">
    <h1 class="no-margin clearfix">
        <?= Html::encode($this->title) ?>
    </h1>
    <hr>
    <div style="overflow: auto">
        <?= $this->render('_form', [
            'model' => $model,
        ]) ?>
    </div>
</div>

modules/admin/views/article/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Новости';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="article-index">

    <h1 class="no-margin clearfix">
        <?= Html::encode($this->title) ?>
        <div class="pull-right">
            <a href="<?=Url::to(['create'])?>" class="btn btn-success">
                <span class="glyphicon glyphicon-plus"></span>
                <span class="hidden-xs hidden-sm">Добавить новость</span>
            </a>
        </div>
    </h1>
    <hr>
    <div style="overflow: auto;">
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'rowOptions' => function ($model){
                return $model->deleted ? ['class' => 'danger'] : [];
            },
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],

                //'id',
                'name',
                [
                    'attribute' => 'author_id',
                    'format' => 'raw',
                    'value' => function($model) {
                        return Html::a($model->author->username, ['identity/view', 'id' => $model->author_id]);
                    }
                ],
                'deleted:boolean',
                'created_at:datetime',
                'updated_at:datetime',

                ['class' => 'yii\grid\ActionColumn'],
            ],
        ]); ?>
    </div>


</div>

modules/admin/views/article/rubrics.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $model app\models\db\Article */
/* @var $rubrics array */

$this->title = 'Рубрики статьи';
$this->params['breadcrumbs'][] = ['label' => 'Новости', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="article-rubrics">
    <h1 class="no-margin clearfix"><?=$this->title?></h1>
    <hr>
    <?php ActiveForm::begin()?>
        <?php foreach ($rubrics as $id => $name):?>
            <div class="form-group">
                <?=Html::checkbox("rubrics[{$id}]", key_exists($id, $model->rubrics), [
                    'label' => $name
                ])?>
            </div>
        <?php endforeach;?>
        <div class="form-group">
            <?= Html::submitButton('Применить', ['class' => 'btn btn-primary']) ?>
        </div>
    <?php ActiveForm::end()?>
</div>

modules/admin/views/article/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\db\Article */

$this->title = 'Редактировать новость';
$this->params['breadcrumbs'][] = ['label' => 'Новости', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Редактировать';
?>
<div class="article-update">
    <h1 class="no-margin clearfix">
        <?= Html::encode($this->title) ?>
    </h1>
    <hr>
    <div style="overflow: auto">
        <?= $this->render('_form', [
            'model' => $model,
        ]) ?>
    </div>
</div>

modules/admin/views/article/view.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\db\Article */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Новости', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="article-view">

    <h1 class="no-margin clearfix">
        <?= Html::encode($this->title) ?>
        <div class="pull-right">
            <a href="<?=Url::to(['update', 'id' => $model->id])?>" class="btn btn-primary">
                <span class="glyphicon glyphicon-pencil"></span>
                <span class="hidden-xs hidden-sm">Редактировать</span>
            </a>
            <a href="<?=Url::to(['rubrics', 'id' => $model->id])?>" class="btn btn-info">
                <span class="glyphicon glyphicon-tags"></span>
                <span class="hidden-xs hidden-sm">Рубрики</span>
            </a>
            <a href="<?=Url::to(['delete', 'id' => $model->id])?>" class="btn btn-danger" data-method="POST" data-confirm="Удалить?">
                <span class="glyphicon glyphicon-trash"></span>
                <span class="hidden-xs hidden-sm">Удалить</span>
            </a>
        </div>
    </h1>
    <hr>
    <div style="overflow: auto">
        <?= DetailView::widget([
            'model' => $model,
            'attributes' => [
                'id',
                [
                    'attribute' => 'author_id',
                    'format' => 'html',
                    'value' => $model->author_id
                        ? Html::a($model->author->username, ['identity/view', 'id' => $model->author_id])
                        : null,
                ],
                [
                    'attribute' => 'image',
                    'format' => 'raw',
                    'value' => function($model) {
                        return Html::a($model->image, [$model->image], ['target' => 'blank']);
                    }
                ],
                'name',
                'body:html',
                'deleted:boolean',
                'created_at:datetime',
                'updated_at:datetime',
            ],
        ]) ?>
    </div>

</div>