modules/admin/controllers/RubricController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\models\db\Rubric;
use yii\base\Exception;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * RubricController implements the CRUD actions for Rubric model.
 */
class RubricController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Rubric models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Rubric::find()->with('parent'),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Rubric model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Rubric model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     * @throws Exception
     */
    public function actionCreate()
    {
        $model = new Rubric();

        if ($model->load(Yii::$app->request->post()) and $model->validate()) {

            /** Устанавливаем превью картинки */
            if($file = UploadedFile::getInstance($model, 'image')) {

                /** Генерируем имя файла */
                $filename = md5(Yii::$app->security->generateRandomString()).".".$file->extension;

                if($uploaded = $file->saveAs(Yii::getAlias("@webroot/upload/{$filename}"))) {
                    $model->image = Yii::getAlias("@web/upload/{$filename}");
                } else {
                    $model->image = $model->oldAttributes['image'];
                }
            } else {
                $model->image = $model->oldAttributes['image'];
            }

            /** Сохраняем */
            if($model->save()) {
                Yii::$app->session->addFlash('success', 'Рубрика успешно была добавлена');
            } else {
                Yii::$app->session->addFlash('error', 'Ошибка сохранения рубрики');
            }

            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
            'rubrics' => $this->findRubrics()
        ]);
    }

    /**
     * Updates an existing Rubric model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     * @throws Exception
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) and $model->validate()) {

            /** Устанавливаем превью картинки */
            if($file = UploadedFile::getInstance($model, 'image')) {

                /** Генерируем имя файла */
                $filename = md5(Yii::$app->security->generateRandomString()).".".$file->extension;

                if($uploaded = $file->saveAs(Yii::getAlias("@webroot/upload/{$filename}"))) {
                    $model->image = Yii::getAlias("@web/upload/{$filename}");
                } else {
                    $model->image = $model->oldAttributes['image'];
                }
            } else {
                $model->image = $model->oldAttributes['image'];
            }

            /** Сохраняем */
            if($model->save()) {
                Yii::$app->session->addFlash('success', 'Рубрика успешно была обновлена');
            } else {
                Yii::$app->session->addFlash('error', 'Ошибка обновления рубрики');
            }

            return $this->redirect(['view', 'id' => $model->id]);

        }

        return $this->render('update', [
            'model' => $model,
            'rubrics' => $this->findRubrics()
        ]);
    }

    /**
     * Deletes an existing Rubric model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Rubric model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Rubric the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Rubric::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    /**
     * Получение списка рубрик для передачи в представление
     * @return array
     */
    protected function findRubrics()
    {
        return Rubric::find()->select(['name'])->indexBy('id')->where(['deleted' => false])->column();
    }
}

modules/admin/views/rubric/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\db\Rubric */
/* @var $form yii\widgets\ActiveForm */
/* @var $rubrics array */
?>

<div class="rubric-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'parent_id')->dropDownList($rubrics, ['prompt' => '---Выберите родительскую рубрику---']) ?>

    <?= $form->field($model, 'image')->fileInput() ?>

    <?= $form->field($model, 'deleted')->checkbox() ?>

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/admin/views/rubric/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\db\Rubric */
/* @var $rubrics array */

$this->title = 'Добавить рубрику';
$this->params['breadcrumbs'][] = ['label' => 'Рубрики', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="rubric-create">
    <h1 class="no-margin clearfix">
        <?= Html::encode($this->title) ?>
    </h1>
    <hr>
    <div style="overflow: auto">
        <?= $this->render('_form', [
            'model' => $model,
            'rubrics' => $rubrics
        ]) ?>
    </div>
</div>

modules/admin/views/rubric/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Рубрики';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="rubric-index">

    <h1 class="no-margin clearfix">
        <?= Html::encode($this->title) ?>
        <div class="pull-right">
            <a href="<?=Url::to(['create'])?>" class="btn btn-success">
                <span class="glyphicon glyphicon-plus"></span>
                <span class="hidden-xs hidden-sm">Добавить рубрику</span>
            </a>
        </div>
    </h1>
    <hr>
    <div style="overflow: auto;">
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'rowOptions' => function ($model){
                return $model->deleted ? ['class' => 'danger'] : [];
            },
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],

                //'id',
                'name',
                'level',
                [
                    'attribute' => 'parent_id',
                    'format' => 'raw',
                    'value' => function($model) {
                        return Html::a($model->parent->name, ['rubric/view', 'id' => $model->parent_id]);
                    }
                ],
                //'image',
                'deleted:boolean',
                'created_at:datetime',
                'updated_at:datetime',

                ['class' => 'yii\grid\ActionColumn'],
            ],
        ]); ?>
    </div>
</div>

modules/admin/views/rubric/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\db\Rubric */
/* @var $rubrics array */

$this->title = 'Редактировать рубрику';
$this->params['breadcrumbs'][] = ['label' => 'Рубрики', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Редактировать';
?>
<div class="rubric-update">
    <h1 class="no-margin clearfix">
        <?= Html::encode($this->title) ?>
    </h1>
    <hr>
    <div style="overflow: auto">
        <?= $this->render('_form', [
            'model' => $model,
            'rubrics' => $rubrics
        ]) ?>
    </div>
</div>

modules/admin/views/rubric/view.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\db\Rubric */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Рубрики', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="rubric-view">

    <h1 class="no-margin clearfix">
        <?= Html::encode($this->title) ?>
        <div class="pull-right">
            <a href="<?=Url::to(['update', 'id' => $model->id])?>" class="btn btn-primary">
                <span class="glyphicon glyphicon-pencil"></span>
                <span class="hidden-xs hidden-sm">Редактировать</span>
            </a>
            <a href="<?=Url::to(['delete', 'id' => $model->id])?>" class="btn btn-danger" data-method="POST" data-confirm="Удалить?">
                <span class="glyphicon glyphicon-trash"></span>
                <span class="hidden-xs hidden-sm">Удалить</span>
            </a>
        </div>
    </h1>
    <hr>
    <div style="overflow: auto">
        <?= DetailView::widget([
            'model' => $model,
            'attributes' => [
                'id',
                'name',
                [
                    'attribute' => 'parent_id',
                    'format' => 'html',
                    'value' => $model->parent_id
                        ? Html::a($model->parent->name, ['rubric/view', 'id' => $model->parent_id])
                        : null,
                ],
                'level',
                'image',
                'deleted:boolean',
                'created_at:datetime',
                'updated_at:datetime',
            ],
        ]) ?>
    </div>

</div>